jep/1/README.adoc
Based on feedback from @bitwiseman on #1
=> Incorporate much of @bitwiseman's feedback, make JEP-1 conform to JEP-1

jep/1/README.adoc
Abstract made really abstract.
Remove the rest of the you pronouns.
Added process overview place holder.
=> Additional changes

jep/1/README.adoc
Address more of the feedback for @oleg-nenashev.
=> Address more of feedbackJep 1

jep/1/README.adoc
=> Additional Reasoning and tweaks

jep/1/README.adoc
=> Added Security and Infra

jep-template/0000/README.adoc
=> Typos and a hyperlink in the template

jep/1/README.adoc
Since GitHub will not allow you to fork the same repo twice.
@reviewbybees
=> Noting that it may be necessary to pick a uniquified branch name when submitting

jep-template/0000/README.adoc, jep/1/README.adoc
Initially proposed by @oleg-nenashev in https://github.com/jenkinsci/jep/pull/15#pullrequestreview-65480476 but I independently noticed that this was absent and generally desirable.
See [this section](https://gist.github.com/jglick/9721427da892a9b2f75dc5bc09f8e6b3#testing) of a pre-JEP proposal of mine for an example.
=> Add testing section

jep/0000/README.adoc, jep/200/README.adoc
[JENKINS-47736](https://issues.jenkins-ci.org/browse/JENKINS-47736)
Matches https://github.com/jenkinsci/jenkins/pull/3120.
=> [JENKINS-47736] Draft JEP: Switch Remoting/XStream blacklist to a whitelist

jep/200/README.adoc
I guess @bitwiseman forgot this.
=> Fixing number

jep/1/README.adoc
=> Minor fixes to JEP-1

jep/1/README.adoc
Motivated by https://github.com/jenkinsci/jep/pull/31
=> Add clarifications after reading Nicolas' JEP draft

jep/1/README.adoc
As compared to #25, this is what I actually want, not what I tried to infer someone else wanted.
=> Simplified branch handling

README.adoc, jep/2/README.adoc
=> Move JEP-2 to master

jep/200/README.adoc
=> Move Jep-200 to master

jep/201/README.adoc
@jenkinsci/jep-editors 
@ewelinawilkosz2
@reviewbybees esp. @ndeloof
=> Various typos and small improvements

jep/200/README.adoc
=> Selecting BDFL delegate for JEP-200

jep/200/README.adoc
- Added some comments/proposed changes to the specification
- Added a "Rollout" section. I feel we need to add it to the JEP Template as well
- Linked the discussion in the ML
@jglick @bitwiseman
=> [JEP-200] - Initial feedback

jep/200/README.adoc
This change reflects the current state:
@jenkinsci/jep-editors @jglick @raul-arabaolaza @dwnusbaum
=> [JEP-200] - Update the state of JEP-200 and accept it

jep/200/README.adoc
Reflecting merge of https://github.com/jenkinsci/jenkins/pull/3120.
@reviewbybees @oleg-nenashev
=> [JEP-200] Marked as Final, and recording some late changes

jep/3/README.adoc
It is a follow-up to the old thread: https://groups.google.com/forum/#!topic/jenkinsci-dev/wzc4VLplHvs
CC @daniel-beck @i386 @orrc @uhafner who participated in the original discussion
=> [JEP-3] - Adding the "Released As" field and "Ready for Release" status to Jenkins JIRA

jep/201/README.adoc
This one IMO is no brainer because ...
* People who worked in this area before, including myself, are very happy to see this effort
* From what I've heard from @ewelinawilkosz and @ndeloof, people who have seen it are excited as well, not to mention the popularity of [JENKINS-31094](https://issues.jenkins-ci.org/browse/JENKINS-31094)
* [To the extent this was discussed in the dev list](https://groups.google.com/d/msg/jenkinsci-dev/_l8UBjCP1vQ/65nC-B7LBgAJ), reaction has been very supportive
* Effort is well underway
=> Accepting JEP #201 as BDFL

jep/300/README.adoc
Evergreen is the name for the distribution system components behind the scenes. :clap:
=> Make a brief mention of Evergreen in relation to JEP-300

jep/3/README.adoc, jep/300/README.adoc, jep/README.adoc
./enumerate-jeps should be run after any status changes are merged.
=> Properly update the statuses in the index page.

jep/300/README.adoc
=> One too many letters

jep/400/README.adoc, jep/README.adoc
=> JEP-400: DRAFT - Jenkins X: Jenkins for Kubernetes CD

jep-template/0000/README.adoc
=> Add missing space

jep/0000/README.adoc, jep/302/README.adoc, jep/README.adoc
[JENKINS-49406](https://issues.jenkins-ci.org/browse/JENKINS-49406)
* [Draft PR](https://github.com/batmat/jep/pull/1) to process feedback from people on the dev ML 
* [Jenkins Essentials' JEP-300](https://github.com/jenkinsci/jep/tree/master/jep/300)
* [Jenkins Essentials' JEP-301](https://github.com/jenkinsci/jep/tree/master/jep/301)
@jenkinsci/jep-editors
=> [JENKINS-49406] Evergreen snapshotting data safety system JEP

jep/201/README.adoc
=> Fix typo in commenting

jep/1/README.adoc
Explicitly state that plugins can be the subject of a jep.
Could JEPs be used as:
* a declaration of intent for a new plugin
* a specification for the design of a new plugin
* a enhancement proposal for an existing plugin
@batmat
=> A plugin can have jep

jep/303/README.adoc, jep/README.adoc
Just doing some Draft busywork @jenkinsci/jep-editors
=> Number and mark JEP-303 in Draft status

jep/0000/README.adoc, jep/304/README.adoc, jep/README.adoc
[JENKINS-49805](https://issues.jenkins-ci.org/browse/JENKINS-49805)
Thanks @jenkinsci/jep-editors
=> [JENKINS-49805] Essentials Client Error Telemetry Logging

jep/304/README.adoc
cc @jenkinsci/jep-editors esp. @rtyler, and @jglick who reviewed the original draft too.
=> [JEP-304] Some draft adjustments / clarifications

jep/0000/README.adoc, jep/305/README.adoc, jep/README.adoc
[JENKINS-50686](https://issues.jenkins-ci.org/browse/JENKINS-50686)
@jenkinsci/jep-editors
=> Publishing incremental commits as Maven releases

jep/202/README.adoc
=> Wrong compress-artifacts PR

jep/202/README.adoc
For the context of how I select BDFL delegate, please see here:
https://groups.google.com/forum/#!msg/jenkinsci-dev/spDAr8EJm3c/ba-ppaM7BgAJ
This part of the core has been worked on by many people, and any of them
can be a BDFL delegate to this JEP. That said, Jesse has worked more
recently on the artifact manager API, and I know he's involved in this
effort quite extensively. So I think he's the best person to ensure
consensus on this effort.
Signed-off-by: Kohsuke Kawaguchi <kk@kohsuke.org>
=> Assigning BDFL delegate for JEP-202

jep/0000/README.adoc, jep/306/README.adoc, jep/README.adoc
https://issues.jenkins-ci.org/browse/JENKINS-50294
@jenkinsci/jep-editors
=> [JENKINS-50294] Essentials Instance Client Health Checking

jep/1/README.adoc
@ewelinawilkosz @jenkinsci/jep-editors @kohsuke
https://groups.google.com/d/topic/jenkinsci-dev/tw0ETwvboAM/discussion
=> JEP process clarification 

jep/305/README.adoc
After [HOSTING-556](https://issues.jenkins-ci.org/browse/HOSTING-556) this is the more natural home.
=> Moved user guide

jep/0000/README.adoc, jep/5/README.adoc, jep/README.adoc
@alyssat and I are working on getting the Jenkins Ambassador program going.  Starting this PR to gather early feedback.
=> [JEP-5] - Jenkins Ambassador Program

jep/1/README.adoc
=> [JEP-1] - Add status update to the "Approve as draft" process

jep/5/README.adoc
The Reasoning section will be for closed design choices not open questions.
=> Move open questions to Specification

jep/304/README.adoc
@jenkinsci/jep-editors esp. @rtyler
=> Make exception field an object

jep-0000/0000/README.adoc, jep/6/README.adoc, jep/README.adoc
Discussion: https://groups.google.com/d/msg/jenkinsci-dev/HaYzG1YVuJI/h_8YzraUCwAJ
=> Jenkins CVE Numbering Authority

jep-0000/README.adoc, jep/7/README.adoc, jep/README.adoc
[Previously](https://groups.google.com/d/msg/jenkinsci-dev/Ve0fqAud3Mk/MTIxw6ZyBwAJ)
=> Add JEP for ruby-runtime deprecation

jep/5/README.adoc
@alyssat @oleg-nenashev 
Does this address the questions?
=> Jenkins ambassador updates

0000/README.adoc, jep/205/README.adoc, jep/README.adoc
following discussion on https://groups.google.com/forum/#!msg/jenkinsci-dev/Bb4pIdpMMIY/OOPL-s2lAgAJ
cc @bitwiseman
=> Declarative Data Binding

jep/set-jep-status
Because I don't want to read the script to understand how to use it.
=> Add usage instructions

jep-template/0000/README.adoc
@jenkinsci/jep-editors @kohsuke 
Uncomment BDFL-Delegate by default
Added date format guidance
Improved instructions in various sections
=> Template update

jep/5/README.adoc, jep/README.adoc
@kohsuke 
This is a request to review this JEP for accepted status.
=> Accept JEP 5

jep/6/README.adoc, jep/README.adoc
Draft discussion: https://groups.google.com/d/msg/jenkinsci-dev/HaYzG1YVuJI/h_8YzraUCwAJ
A few questions asking for clarification that IMO don't need content changes.
=> Accept JEP-6

jep/201/README.adoc
Based on a discussion with @ndeloof and @ewelinawilkosz last week, I'm restructuring JEP-201. 
Significant portions of the removed text will be resurrected in follow-up JEPs on CasC Tooling and CasC Schema.
=> Preparing JEP-201 for Review

jep/307/README.adoc
@jenkinsci/jep-editors thanks!
=> Fix two small typos

jep/201/README.adoc, jep/README.adoc
@oleg-nenashev @jglick @kohsuke 
https://github.com/jenkinsci/jep/pull/108 provides context for the changes made to this JEP. 
There are at least to follow up JEPs in the pipe: tooling and schema.
=> Accept JEP-201

jep/2/README.adoc, jep/200/README.adoc, jep/201/README.adoc, jep/202/README.adoc, jep/203/README.adoc, jep/204/README.adoc, jep/205/README.adoc, jep/3/README.adoc, jep/301/README.adoc, jep/302/README.adoc, jep/303/README.adoc, jep/304/README.adoc, jep/305/README.adoc, jep/306/README.adoc, jep/307/README.adoc, jep/308/README.adoc, jep/309/README.adoc, jep/4/README.adoc, jep/7/README.adoc, jep/README.adoc, jep/enumerate-jeps, jep/set-jep-status
=> Add sponsor to JEP table

jep/0000/README.adoc, jep/206/README.adoc, jep/README.adoc
Submitted for approval as draft JEP by @jenkinsci/jep-editors.
@kohsuke I do not know who the BDFL delegate should be.
=> Use UTF-8 for Pipeline build logs

jep/305/README.adoc
Matches https://github.com/jenkinsci/incrementals-tools/pull/6. @batmat etc.
=> [JENKINS-51869] [JEP-305] Drop of --first-parent and its justification

jep/0000/README.adoc, jep/310/README.adoc, jep/README.adoc
[JENKINS-52210](https://issues.jenkins-ci.org/browse/JENKINS-52210)
cc @mandie722 @rtyler
=> [JENKINS-52210] Essentials AWS auto-configuration

jep/0000/README.adoc, jep/207/README.adoc, jep/README.adoc
https://issues.jenkins-ci.org/browse/JENKINS-52691
@carlossg @jglick @jenkinsci/jep-editors
=> New JEP: External Build Logging support in the Jenkins core

jep/207/README.adoc
=> [JEP-207] - Copy-edit design decisions and body

README.adoc
@jenkinsci/jep-editors 
Accidentally closed the previous PR.
=> Add video and office hours

jep/0000/README.adoc, jep/8/README.adoc, jep/README.adoc
CC @martinda and @christ66 as GSoC Org admins and also @rtyler as SPI board member and active Jenkins contributor
=> Add new JEP: GSoC Budgeting and Expenses

jep/0000/README.adoc, jep/210/README.adoc, jep/README.adoc
Submitted for approval as draft JEP by @jenkinsci/jep-editors. CC @oleg-nenashev @carlossg @svanoort @abayer @rsandell @dwnusbaum
=> [JENKINS-38381] Draft JEP

jep/8/README.adoc
Fix typo introduced by copy-edits.
=> JEP-8: fix typo

jep/207/README.adoc
As requested by @bitwiseman after merging the JEP draft.
=> [JEP-207] - Add motivation and update links

jep/207/README.adoc, jep/210/README.adoc, jep/211/README.adoc, jep/212/README.adoc
=> Redirect External Logging and Java 10+ discussions to SIGs

jep/0000/README.adoc, jep/213/README.adoc, jep/README.adoc
As discussed before, I have polished my writeup about External Configuration storage and reformatted it as JEP.
CC @deepy @jglick @carlossg
=> JEP Draft: Configuration Storage API in the Jenkins Core

jep/0000/README.adoc, jep/10/README.adoc, jep/README.adoc
New policies for twitter team for Jenkins twitter account.
=> JEP for Jenkins Twitter Team Policy

jep/309/README.adoc
Thread here: https://groups.google.com/d/msgid/jenkinsci-dev/20180814153826.GH17800%40grape.lasagna.io
=> Accept JEP-309

jep/10/README.adoc
Improvements based on community feedback
=> Updates based on community feedback.

jep/0000/README.adoc, jep/11/README.adoc, jep/README.adoc
Submitted for approval as draft JEP by @jenkinsci/jep-editors
=> Add JEP for improving process for adopting a plugin

jep/11/README.adoc
Summarize existing plugin adoption process, as requested by @bitwiseman
=> JEP 11: Summarize the existing plugin adoption process

jep/11/README.adoc
Incorporate some feedback from @daniel-beck about security issues here: https://groups.google.com/d/msg/jenkinsci-dev/BkSipSaSYl8/0R6Ovjc1DwAJ
=> Incorporate feedback about security

jep/206/README.adoc, jep/README.adoc, jep/set-jep-status
The associated PRs were merged, and no further work is planned, so might as well be final, right?
There is still no BDFL delegate. @kohsuke?
I had to fix the status script, which was broken and apparently had not been run in a while either.
=> Finalizing JEP-206

jep/302/README.adoc
Yeah, I'm lazy to look it up myself each time :)
=> Make it easier to browse required JEPs from GitHub UI

jep/303/README.adoc
Our client registration and authentication system is well baked at this time, not that there was any significant feedback here.
I'm happy to mark this as Accepted
=> Accepting JEP-303

jep/202/README.adoc, jep/302/README.adoc, jep/304/README.adoc, jep/310/README.adoc, jep/README.adoc
Ping @rtyler cc @bitwiseman 
cc @jenkinsci/jep-editors
=> More Essentials->Evergreen rebranding lefovers

jep/2/README.adoc
See https://github.com/jenkinsci/jenkins/pull/3626
=> Add languages category

jep/8/README.adoc
=> Minor corrections

jep/210/README.adoc, jep/README.adoc
In fact all the code changes have been merged and (where appropriate) released as beta, so I am not sure if Final would be more appropriate, but I am erring on the conservative side here.
=> Marking JEP-210 as accepted

jep/211/README.adoc
=> [JEP-211] - Update the timeline to reflect the current plan and the EPICs list

jep/211/README.adoc
This change makes some adjustments in the scope according to the current EPICs.
CC @jenkinsci/java11-support
=> [JEP-211] - Clarify the scope

jep/12/README.adoc
@tracymiranda 
I've updated this JEP with the full text from the wikipage. If we accept this merge, we can point the wikipage to this JEP and use this as the source of truth.
=> Integrate full program into JEP

jep/211/README.adoc
=> Add link to Java 11 compatibility issues wiki page

jep/211/README.adoc
As discussed with @batmat and @olblak
=> [JEP-211] - Update Docker packaging for Master to reflect the current labeling practices

jep/211/README.adoc
=> [JEP-211] - Clarify JDK requirements for ci.jenkins.io

jep/211/README.adoc
* https://issues.jenkins-ci.org/browse/JENKINS-20679
* https://issues.jenkins-ci.org/browse/INFRA-1870
See https://groups.google.com/forum/#!topic/jenkinsci-dev/lqQyZnce0qc for the context
@jenkinsci/java11-support
=> [JEP-211] - Document requirements for Minimum-Java-Version and Experimental Update Center for Java 11

jep/205/README.adoc
https://github.com/kohsuke/jep/tree/data-api/jep/0000/1
=> removed meta-model proposal, as this collides with data-api

jep/8/README.adoc
References:
1. Comments for git commit https://github.com/jenkinsci/jep/commit/b7fe523450c1c34a57c61923695d3b9049280dff#comments
2. Pull Request #144
Co-Authored-By: Martin d'Anjou <martin.danjou14@gmail.com>
Cc @martinda @jeffpearce @oleg-nenashev
=> Add suggestions originally from @martinda

jep/211/README.adoc
=> [JEP-211] - Add developer guidelines to the JEP

jep/211/README.adoc
@jenkinsci/java11-support @daniel-beck @Wadeck
=> [JEP-211] - Be explicit about potential security risks in Java 11 preview when running with Java 11

jep/211/README.adoc
=> Tweaks and cleanup

jep/211/README.adoc, jep/README.adoc
Staging the JEP-211 approval pull request. All comments have been addressed, #225 is the last one to be merged. The deadline for feedback in Dev List / Platform SIG was Monday, so we can go forward with accepting it.
@jenkinsci/java11-support @jenkinsci/jep-editors
=> Accept JEP-211 as a BDFL Delegate

jep/217/README.adoc
* Be explicit that the DockerHub organization name is under discussion (CC @bitwiseman )
* Reflect https://github.com/jenkins-infra/pipeline-library/pull/81 in the JEP and the Pipeline example (CC @olblak @rtyler )
@jenkinsci/jep-editors @batmat
=> [JEP-217] - Updates according to the feedback

jep/13/README.adoc, jep/217/README.adoc, jep/8/README.adoc
See commit message for each JEP for my rationale.
=> Assigning BDFL delegates to JEPs

jep/218/README.adoc
=> Update JEP number in intro

jep/207/README.adoc, jep/210/README.adoc, jep/212/README.adoc, jep/README.adoc
Various things I forgot to update here over time.
=> JEP-210 refresh

jep/216/README.adoc
localization-support-plugin had released
=> Update status of localization

jep/0000/README.adoc, jep/220/README.adoc, jep/README.adoc
Yes, this is another Jenkins Security JEP dump. We've developed this JEP during the development of the fix that was published earlier today.
@reviewbybees @daniel-beck @Wadeck @jeffret-b 
Looking for additional reviews outside the team above who has already reviewed this before today.
=> Draft: Dispatchable Views and View Fragments in Stapler

jep/221/README.adoc
There are on going discussions around the underlying design and implementation of this JEP.   I think it makes sense to establish some high-level feature requirements (separate from design/implementation).
=> Highlight required features

jep/8/README.adoc
CC @martinda @markyjackson-taulia
=> JEP-8: Add a comment about economy class upgrades

jep/222/README.adoc
Implemented in https://github.com/jenkinsci/jenkins/pull/4369.
=> [JEP-222] Proposal for a CLI transport

jep/222/README.adoc
Just to make the scope of the JEP more explicit
=> JEP-222: Improve the title

jep/223/README.adoc
CC @mikecirioli @aHenryJard @EstherAF . The current title is a bit too long
=> [JEP-223] - Shorten the JEP title

jep/README.adoc
=> Update the JEP index

jep/224/README.adoc, jep/README.adoc
=> [JEP-224] - Set the status to Draft

jep/223/README.adoc
The previous PR has been closed, this is the new PR link for MANAGE permission.
=> JEP-223 update PR link to new one.

jep/201/README.adoc
Audience -> audience
ressource -> resource
kubernetes -> Kubernetes
Jenking -> Jenkins
possilbe -> possible
=> JEP-201 - Docs(README.adoc): change very minor misspellings

jep/223/README.adoc
=> [JEP-223] minor update to mention the minimal PR and documentation on how to enable the experimental feature

jep-template/0000/README.adoc
=> Fix typo in the JEP template

jep/203/README.adoc, jep/204/README.adoc, jep/README.adoc
Based on https://groups.google.com/forum/#!msg/jenkinsci-dev/zO9VFNxhF-o/EpjdA8-jCgAJ , I do not think this JEPs are going to proceed in foreseeable future. I suggest to explicitly defer them. CC @bitwiseman @jphartley @imeredith who could comment on that.
I am not sure about JEP-215, needs additional feedback
=> Mark Blue Ocean JEPs as deferred (JEP-203, JEP-204) 

jep/224/README.adoc
https://github.com/orgs/jenkinsci/projects/4 ftr
=> JEP-224: Reference the GitHub project

jep/226/README.adoc
CC @oleg-nenashev @afalko @mikecirioli
=> [JEP-226] Add link to prototype demo

.github/FUNDING.yml
Maybe needs https://groups.google.com/forum/#!topic/jenkinsci-dev/iLutO2X0bdg to be approved and finalized before it is merged
=> [JEP-15] - Add FUNDING metadata to the JEP repository

jep/14/README.adoc, jep/README.adoc
As BDFL-delegate, this is the final approval for this JEP.
=> Move JEP-14 to active

jep/226/README.adoc
CC @oleg-nenashev @afalko @mikecirioli
=> JEP-226: Update documentation to reflect the current changes

jep/227/compatibility.adoc
Might add more commits as things come in, but can be merged whenever.
=> JEP-227 updates

jep/227/compatibility.adoc
=> Un-break the format

jep/224/README.adoc, jep/README.adoc
See https://github.com/jenkinsci/jenkins/pull/4909
=> JEP-224 Graduate System Read to GA

jep/227/compatibility.adoc
=> [JEP-227] Update some status and add some PRs

jep/227/compatibility.adoc
Linking to https://github.com/jenkinsci/reverse-proxy-auth-plugin/pull/37 by @fbelzunc.
=> Linking to reverse-proxy-auth-plugin #37 from JEP-227

jep/228/README.adoc, jep/228/compatibility.adoc, jep/README.adoc
Background for https://github.com/jenkinsci/jenkins/pull/4944. FYI @joehni
=> Unforking XStream

jep/227/compatibility.adoc
=> Update JEP-227 after a first bug bash

jep/228/compatibility.adoc
=> https://github.com/jenkinsci/matrix-auth-plugin/pull/89 released

jep/227/compatibility.adoc, jep/228/compatibility.adoc
Matching https://github.com/jenkins-infra/jenkins.io/pull/3880/commits/2ec83c84b5b2dddbfb69d852044e25a259538181 suggested by @Wadeck.
=> Proposing Jira labels for JEP-227 & JEP-228

jep/229/README.adoc
=> JEP-229 updates

jep/229/README.adoc
@daniel-beck https://github.com/jenkins-infra/repository-permissions-updater/pull/1747
=> Linking to repository-permissions-updater #1747

jep/227/compatibility.adoc
https://github.com/jenkinsci/reverse-proxy-auth-plugin/pull/40
=> reverse-proxy-auth-plugin #40 released

jep/227/README.adoc
@jvz & @daniel-beck w.r.t. https://github.com/jenkinsci/jenkins/pull/4848#issuecomment-685945247
=> [JEP-227] Formalizing discussion about 2 suffix

jep/228/README.adoc
https://github.com/x-stream/xstream/issues/101
=> Noting XStream issue

jep/227/compatibility.adoc
@rsandell released https://github.com/jenkinsci/ldap-plugin/pull/49!
=> [JEP-227] Note ldap 2.0

jep/228/compatibility.adoc
https://github.com/jenkinsci/htmlpublisher-plugin/pull/86 released.
=> [JEP-228] htmlpublisher-1.24

jep/227/compatibility.adoc
This PR updates the JEP-227 compatibility table for cas-plugin.
=> Update JEP-227 compatibility for cas-plugin

jep/228/compatibility.adoc
https://github.com/jenkinsci/atlassian-jira-software-cloud-plugin/pull/40
=> [JEP-228] https://github.com/jenkinsci/atlassian-jira-software-cloud-plugin/pull/40 released

jep/228/compatibility.adoc
https://github.com/jenkinsci/allure-plugin/pull/271 @eroshenkoam
=> [JEP-228] Noting allure release

jep/227/compatibility.adoc
https://github.com/jenkinsci/purge-job-history-plugin/pull/10
=> [JEP-227] purge-job-history-plugin #10 released

jep/229/README.adoc
See also https://github.com/jenkinsci/log-cli-plugin/pull/56.
=> [JEP-229] Updates

jep/229/README.adoc
I realized that I had not updated some text to reflect the fact that jenkins-infra/jenkins-maven-cd-action#1 has been implemented.
=> [JEP-229] Noting jenkins-infra/jenkins-maven-cd-action#1

jep/228/compatibility.adoc
jenkinsci/ecutest-plugin#267 released.
=> [JEP-228] ecutest-2.25

jep/227/compatibility.adoc
https://issues.jenkins.io/browse/JENKINS-65233
amending #314 by @Wadeck
=> [JEP-227] Noting JENKINS-65233

jep/227/compatibility.adoc
Amends #314 to note https://github.com/jenkinsci/oic-auth-plugin/issues/105.
=> [JEP-227] Noting oic-auth issue

jep/230/README.adoc, jep/README.adoc
=> Accept "Convert modules to plugins" as a JEP-230 draft

jep/0000/README.adoc
Provides background and refreshed proposals for https://github.com/jenkinsci/jenkins/pull/3988.
=> Draft JEP: Convert modules to plugins

jep/229/README.adoc
Waiting for https://github.com/jenkinsci/.github/pull/48 to be merged so I can add permalinks
=> JEP-229 Update references from log-cli to .github cd.yaml

jep/227/compatibility.adoc
=> [JEP-227] update compatibility.adoc for jobconfighistory

jep/227/compatibility.adoc
mentioned pending link was merged at least
https://github.com/jenkinsci/pipeline-restful-api-plugin/pull/13
=> update compatibility.adoc for pipeline-restful-api

jep/0000/README.adoc, jep/231/README.adoc, jep/README.adoc
=> Create JEP-231: Remove commons-digester dependency from Jenkins Core

jep/231/README.adoc
https://github.com/jenkinsci/jenkins/pull/5320 has been merged and few more plugins released since. This PR updates the table to reflect the current status.
=> [JEP-231] Update plugin update state table

jep/231/README.adoc
https://github.com/jenkinsci/subversion-plugin/pull/259#issuecomment-861609886
=> Mini guide on replacing Digester with plain old Java programming

jep/0000/README.adoc
I think we need a place to have the official, community validated list of words and replacement. I propose to do it in a JEP to have git history.
With possible link in documentation here https://www.jenkins.io/doc/developer/internationalization/
=> [JEP-16] - Inclusive terminology guidelines and continuous updates

jep/231/README.adoc
jenkinsci/teamconcert-plugin#20 was released.
=> Updating JEP-231

jep/228/compatibility.adoc
https://github.com/jenkinsci/gradle-plugin/pull/100 @wolfs
=> [JEP-228] Noting `gradle` plugin release

jep/228/compatibility.adoc
The suggested code to be fixed has been fixed. For changes, see https://github.com/jenkinsci/snyk-security-scanner-plugin/commit/7e8a8f074029bbf56e2259c195cf4cb0133dec67
=> [JEP-228] Update for snyk-security-scanner@3.1.0

jep/202/README.adoc, jep/README.adoc
=> Mark JEP-202 as Final

jep/200/README.adoc, jep/README.adoc
=> JEP-200 - Cleanup the whitelist/blacklist terminology

jep/230/README.adoc
https://github.com/jenkinsci/remoting-opentelemetry-plugin/issues/65#issuecomment-883754559 for context. I need to think about this a bit more.
=> Maybe move `jenkins.slaves.restarter`

jep/7/README.adoc
=> JEP-7 - Add Python Runtime to the scope, document the rollout plan

jep/222/README.adoc, jep/README.adoc
In an LTS; no further work planned for now.
=> Mark JEP-222 as Final

jep/235/README.adoc
See [JENKINS-67337](https://issues.jenkins.io/browse/JENKINS-67337) for details.
=> Reference to GeneXus plugin compatibility fix 

jep/236/README.adoc
Dates have been agreed after discussions with Mark and security team
=> JEP-236 Add timeline for Java 8 EOL

jep/230/README.adoc, jep/README.adoc
Taking into account recent changes. https://github.com/jenkinsci/jenkins/pull/6585
=> JEP-230 edits

jep/230/README.adoc, jep/README.adoc
Shipped https://github.com/jenkinsci/jenkins/pull/6585 in 2.357 so I think it is done.
=> Mark JEP-230 as Final

jep/15/README.adoc
Also a few minor status updates
=> Complete renaming of LFX CommunityBridge to Crowdfunding

jep/202/README.adoc, jep/211/README.adoc, jep/214/README.adoc, jep/236/README.adoc, jep/300/README.adoc, jep/301/README.adoc, jep/302/README.adoc, jep/303/README.adoc, jep/304/README.adoc, jep/306/README.adoc, jep/307/README.adoc, jep/308/README.adoc, jep/310/README.adoc, jep/README.adoc
https://github.com/jenkins-infra/helpdesk/issues/3238 and following up #395. Note that there are numerous references to Evergreen in JEP-305 which I left in since they are embedded in the original motivation.
=> Marking Evergreen JEPs as withdrawn

jep/0000/README.adoc
new Jep for FIPS-140 compliance.
I checked the rendering locally before creating the PR and it looked ok.
```[tasklist]
```
=> FIPS-140 Jep
