jep/1/README.adoc
Extensive reorganizing and tuning. 
There are no changes to the underlying process, except:
* Addition of a `jep-submission` branch with a template for submissions.
* JEP submissions will be number `0000`. 
Probably a ton of typos as usual.  I'll read this again tomorrow and see if I can catch them.
=> Reworking for clarity

jep/1/README.adoc
@jenkinsci/jep-editors 
Having let some previous feedback percolate for a bit, I thought it would be better to have a role that was "JEP Reviewer" instead of "BDFL-delegate".   I also expanded the text for the BDFL role to make it clearer that they have great power and a responsibility to generally avoid using it.
=> Added Reviewer role and updated BDFL

jep/301/README.adoc
This has largely been prototyped and is thus far functional, but I think a
design document is still valuable for discussion and posterity.
=> Add a JEP describing the jenkins/evergreen docker image

jep/300/README.adoc
The nuance of different "flavors" is important, and will need to be incorporated
into future documents as the plugins considered Essential on Azure, for example,
will differ from that on Amazon.
=> Incorporate some feedback and describe the nuance of cloud/environment specific defaults

jep/300/README.adoc
Between the previous rounds of discussions in Jenkins World contributor summit and the recent mailing list discussion, I think there's a consensus of the general problem space.
Tyler will be working on this area, and he has been championing the education/arming of users as well as making Jenkins accessible to the broader users, on top of all the other things he has worked on over the past decade. I think he's well qualified to drive this effort, and as such I intend to delegate subsequent JEPs in this space to Tyler.
Let's give this PR several days before we merge this.
=> Accepting JEP #300 as BDFL

jep/301/README.adoc
For the context of how I select BDFL delegate, please see [here](https://groups.google.com/forum/#!msg/jenkinsci-dev/spDAr8EJm3c/ba-ppaM7BgAJ)
As a sponsor of JEP-300, I consider Tyler to be the leader of this effort, and as such he should be the BDFL delegate of this JEP.
=> Assigning BDFL delegate for JEP-301

jep/302/README.adoc
For the context of how I select BDFL delegate, please see here:
https://groups.google.com/forum/#!msg/jenkinsci-dev/spDAr8EJm3c/ba-ppaM7BgAJ
As a sponsor of JEP-300, I consider Tyler to be the leader of this
effort, and as such he should be the BDFL delegate of this JEP.
=> Assigning BDFL delegate for JEP-302

jep/303/README.adoc
This does not fundamentally change the nature of the design, just an
detail discovered during implementation regarding functionality gaps in the
Node.js ECDH tooling.
See also: https://github.com/jenkins-infra/evergreen/pull/42/commits/26c46b7ecf104562a42384dd7162eb1834801029
=> Evergreen client registration is actually using ECDSA rather than ECDH

jep/304/README.adoc
JSON allows many possible encoding. We restrict it to UTF-8 only for simplicity.
>[JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.  The default
encoding is UTF-8, and JSON texts that are encoded in UTF-8 are
interoperable in the sense that they will be read successfully by the
maximum number of implementations; there are many implementations
that cannot successfully read texts in other encodings (such as
UTF-16 and UTF-32).](https://tools.ietf.org/html/rfc7159#section-8.1)
=> Require UTF-8 for simplicity

jep/201/README.adoc, jep/README.adoc
Based clarifications in PR #76, this JEP is being
returned to Draft.  This is specifically because
the design and scope of this JEP are still being
worked out.  Support for this JEP remains strong,
implementation is in progress, and we fully expect
this JEP will be accepted once the scope and design
discussions are complete.
@ewelinawilkosz @ndeloof @kohsuke @jenkinsci/jep-editors
=> Reset JEP-201 to Draft

jep/303/README.adoc
Since this has now been implemented, worth including.
=> Include the actual request content and headers for the registration/auth flow

jep/304/README.adoc, jep/305/README.adoc
Assigning BDFL delegate for JEP-30x
For the context of how I select BDFL delegate, please see here:
https://groups.google.com/forum/#!msg/jenkinsci-dev/spDAr8EJm3c/ba-ppaM7BgAJ
As a sponsor of JEP-300, I consider Tyler to be the leader of this
effort, and as such he should be the BDFL delegate of this JEP.
=> Assining BDFL delegates to 30x JEPs

jep/202/README.adoc
As suggested by @oleg-nenashev in #96, enumerating plugins known to be using APIs which would clash with remote artifact storage. CC @carlossg
=> Fleshing out backwards compatibility section of JEP-202

jep/1/README.adoc
@jenkinsci/jep-editors 
This does not functionally change the meaning of the  JEP.  It only gathers all the text on approval as draft to actually be under the "Approval as Draft" section.
=> Rearrange text for approval as draft

jep/202/README.adoc
In case https://github.com/jenkinsci/jenkins/pull/3480 is merged.
=> JEP-202 updates, esp.: remove FilePath.copyFromRemotely from API

jep/0000/README.adoc, jep/211/README.adoc, jep/README.adoc
This JEP draft summarizes the current plan regarding Java 10 (and tentatively Java 11) support in Jenkins. This JEP depends on #135 which would be a venue for the JEP discussion.
@jenkinsci/jep-editors @kohsuke @bitwiseman @tracymiranda
=> JEP Draft: “Java 10 and Java 11 support in Jenkins”

jep/README.adoc
Looks like there was a typo in the URL
=> Fix link to Ewelina Wilkosz profile on GitHub

jep/README.adoc, jep/enumerate-jeps
Makes for a slimmer file header, allows the edit button to appear immediately, and in conjunction with [this invaluable Chrome extension](https://chrome.google.com/webstore/detail/make-github-pages-full-wi/dfpgjcidmobcpaoolhgchdcmdgenbaoa) avoids gratuitous restriction of width.
Before:
After:
=> Link to README.adoc rather than its containing directory

jep/0000/README.adoc, jep/208/README.adoc, jep/README.adoc
@ewelinawilkosz 
@bitwiseman 
@rtyler
=> Configuration as Code tooling proposal

jep/0000/README.adoc, jep/209/README.adoc, jep/README.adoc
@ndeloof @ewelinawilkosz 
I pulled the text from JEP-201 to here.  This is a placeholder for the Configuration as Code YAML Schema JEP.  
Before this can be approved as Draft,  it seems to me that most of the Specification needs rewriting/filling in - describing how the schema we be generated and the APIs for customizing the schema when the automatically generated schema is not sufficient. 
However, I don't have the expertise to write that. 
You can either update this PR or pull the branch and start your own.
=> Configuration as Code YAML Schema

jep/210/README.adoc
Just stumbled across the `aws-cloudwatch-logs-publisher-plugin` repo today and felt I needed to explain why this JEP does not duplicate that kind of feature.
@oleg-nenashev @jenkinsci/jep-editors
=> Added a new reasoning section about cloud log mirroring plugins

jep/212/README.adoc
@svanoort @oleg-nenashev @jglick 
This is an alternative to #159 . 
Either of these formats could be addressed by responding with comment or edits or the blocks could be  merged for later editing/response.  They would make it possible to have some degree of design discussion within the JEP (contained in the history) but also retain the final form of the JEP a design document (not a discussion thread).
This one as the advantage that questions/comments visible in the document.  It would make it easy to see  what the open questions/discussion are and be able to respond to them. The other format would make the JEP look more like it's final form (hidding comments/questions) from top level view. 
We could of course also use both as people felt appropriate.
=> Added comments/questions from svanoort

jep/309/README.adoc
This change continues the implementation of the BOM format specification. By now Custom War Packager has been released in 1.0, and there are also many updates in Evergreen. IMHO it is a good time to get this story over the fence.
@carlossg @jglick @bitwiseman @rtyler
=> [JEP-309] - Extend specification and reasoning

jep/210/README.adoc
Moved a “reasoning” block from https://github.com/jenkinsci/workflow-job-plugin/pull/27. Also adjusting wording to reflect the fact that https://github.com/jenkinsci/jenkins/pull/3563 was merged.
=> Updated JEP-210

jep-template/0000/README.adoc, jep/309/README.adoc
Just fixing the JEP formatting
Before:
=> JEP-209: Summary table generation script does not support multi-line sponsor cells

jep/207/README.adoc, jep/212/README.adoc
This change aligns the JEP with the new implementation in https://github.com/jenkinsci/jenkins/pull/3575
Implementations:
* https://github.com/jenkinsci/jenkins/pull/3575
* https://github.com/jenkinsci/external-logging-api-plugin/pull/2
* https://github.com/jenkinsci/external-logging-elasticsearch-plugin/pull/2
Also CC @carlossg who is a BDFL delegate in JEP-212
=> [JEP-207, JEP-212] - Address comments from @jglick

jep/206/README.adoc
@svanoort asked about this topic in https://github.com/jenkinsci/durable-task-plugin/pull/60#discussion_r208308043.
=> Use of non-ASCII-embedding encodings

jep/310/README.adoc
I had specified it, but forgotten to remove the `// `
Followup for https://github.com/jenkinsci/jep/pull/140
=> [JEP-310] Uncomment the associated JIRA ID

jep/set-jep-status
`sed -i` works differently on mac versus *nix.
=> Fix set-jep-status for mac

jep/211/README.adoc
Java 10 is EoL starting from Sep 25, 2018. There is no sense to support Java 10 anymore.
I propose to go straight to Java 11.
@jenkinsci/jep-editors @MarkEWaite
=> JEP-211: Target Java 11 support only.

jep/211/README.adoc
Maybe we need the same team for jenkins-infra, not sure.
CC @jenkinsci/java11-support
=> [JEP-211] - Explicitly add Java 11 Support Team to the JEP

jep/210/README.adoc
After https://github.com/jenkinsci/pipeline-cloudwatch-logs-plugin/pull/12.
=> Fixing links to pipeline-cloudwatch-logs

jep/211/README.adoc
CC @batmat @jenkinsci/java11-support 
It's a follow-up to https://issues.jenkins-ci.org/browse/JENKINS-51998?focusedCommentId=355675&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-355675
=> [JEP-211] - Add Reasoning about Java 10 and Java 12 support

jep/0000/README.adoc, jep/217/README.adoc, jep/README.adoc
As discussed at the previous SIG meeting, we want to deploy an infrastructure to allow building experimental images on ci.jenkins.io. I have spent some time to draft a JEP which documents the process.
I believe that @olblak could be the best BDFL Delegate for this JEP
CC @jenkinsci/sig-platform
=> JEP Draft: Experimental Jenkins organization on DockerHub

jep/8/README.adoc
@oleg-nenashev @jeffpearce @lloydchang 
I wanted to add details to the org admin expense approval process in case an org admin is not available or cannot be reached.
I also clarified that expense request approval decisions are made by consensus.
=> Org admin approval process details

jep/0000/README.adoc, jep/13/README.adoc, jep/README.adoc
As a follow-up to the recent discussions in GSoC SIG and in JCasC project, I have created a JEP to document process of requesting YouTube Manager permissions. In this JEP I have briefly documented the process and the responsibilities of managers.
I have not provided explicit guidelines on how to manage/label video recordings, but it can be added later if needed
CC @bitwiseman @jenkinsci/sig-gsoc @ewelinawilkosz
=> Draft Process JEP for YouTube management

jep/0000/README.adoc, jep/219/README.adoc, jep/README.adoc
Submitted for approval as draft JEP by @jenkinsci/jep-editors.
=> Add Jenkins Operator Draft

jep-template/0000/README.adoc
I was reviewing the guidance here (which is very good!) to determine how to properly author a Jenkins Enhancement Proposal (JEP). I found a few things that needed a bit of polish. No policy changes - only wording.
=> Fixed typos and some stylistic/grammar things

jep/0000/README.adoc, jep/221/README.adoc, jep/README.adoc
This proposal, once complete, will describe a mechanism by which Jenkins plugin maintainers could choose to have their plugins released upon merging to a particular branch. This merge operation would trigger a webhook, which would in turn trigger a build/test/deploy cycle from a trusted CI server managed by the Jenkins infrastructure team.
=> Draft: Opt-In Continuous Delivery of Jenkins Plugin Releases

jep/305/README.adoc, jep/README.adoc
Just noticed this was still in Draft status, which is not right—it is long since implemented and in widespread use. (Certainly there are various open RFEs and the like, but that will always be true.)
=> Marking JEP-305 as Final

jep/0000/README.adoc, jep/222/README.adoc, jep/README.adoc
Prototype implementation in https://github.com/jenkinsci/jenkins/pull/4369 and its upstreams.
=> JEP draft: WebSocket Services

jep/222/README.adoc
Noting https://github.com/jenkinsci/docker-jnlp-slave/pull/130 + https://github.com/jenkinsci/kubernetes-plugin/pull/661, a newly introduced `-webSocket` agent CLI option, and some more background about mode switch and encryption.
=> Amendments to JEP-222

README.adoc
We do not longer have JEP Meetings, and there is no immediate plan to remove them. I suggest just removing the sentence for now
=> README: Remove the reference to defunct JEP meetings

jep/222/README.adoc
CloudBees documentation got rearranged and broke a link.
=> Fixed 404 in JEP-222 references

jep/223/README.adoc
This PR addresses the following feedback from @daniel-beck and @jvz :
- This is a fairly complex change with no commitment to address regressions (like JEP-200 did). 
- If there are still plugins using the deprecated Plugin#configure  mechanism, their configuration appears to be always hidden from Jenkins/Configure via GlobalPluginConfiguration#configure . We're probably good with that?
> Plugins that contribute to the settings on on the Configure Jenkins page should carefully consider if allowing a user with only Jenkins.CONFIGURE could result in an unintended privelege escalation.
- This sounds like a fairly onerous requirement for plugins. Based on the numerous published security advisories just around plugins not bothering with a permission check in the first place, this sounds like a …
=> Address JEP-223 feedback

jep/10/README.adoc, jep/13/README.adoc, jep/4/README.adoc, jep/README.adoc
We are actively using JEPs for SIGs, Twitter and YouTube in the community's day-to-day work. And they work pretty well. These are the process JEPs, and hence they can be adjusted later if needed. So I would suggest to mark these JEPs as active.
This change requires approvals from @rtyler and @bitwiseman who were assigned as BDFL delegates
=> [JEP-4, JEP-10, JEP-13] - Mark SIG, Twitter and YouTube JEPs as active

jep/12/README.adoc, jep/README.adoc
I am doing a cleanup of draft JEPs, and this one is pretty important because of the [Funding rework](https://groups.google.com/forum/#!msg/jenkinsci-dev/iLutO2X0bdg/qcEpxS1iBgAJ) I am doing in the background. This process JEP is well-written and covers main items, so I would propose to call it an active one.
Later we may need to move bits from JEP-8 about using travel budget into this JEP: https://github.com/jenkinsci/jep/tree/master/jep/8#using-the-budget . If @tracymiranda prefers to have it done first, I will mighrate the content.
=> Mark JEP-12 "Travel grant program" as active

jep/14/README.adoc, jep/218/README.adoc, jep/220/README.adoc, jep/224/README.adoc, jep/README.adoc
As discussed with @slide @daniel-beck, I suggest them as BDFL delegates for JEP-14, JEP-218, JEP-220. I would also like to beome a BDFL delegate for JEP-224 as discussed with @timja. Ultimately this PR needs sign-off/merge by @kohsuke to become valid according to our JEP process
=> Assign BDFL delegates to JEP-14, JEP-218, JEP-220 and JEP-224

jep/223/README.adoc
To be more complete and accurate about the JEP, it seems better to use the EPIC link as Jira link.
=> [JEP-223] Using Epic JIRA instead of the first PR Jira

jep/226/README.adoc, jep/README.adoc
CC @oleg-nenashev @afalko @mikecirioli
=> Introduce JEP for External Fingerprint Storage

jep/226/README.adoc
Why am I doing this? I now realise that it does not make sense to keep the build pointers to a fingerprint updated if we have to run a periodic job anyway. Might as well use it to update the build pointers, just like the current implementation does it.
I have also proposed revamping the current fingerprint cleanup to use the new API, so it becomes homogenous.
@oleg-nenashev @afalko @mikecirioli  Would love to hear your thoughts, as this is highly important for the next steps :)
=> [JEP-226] Improve section on fingerprint cleanup

jep/227/compatibility.adoc
In https://github.com/jenkinsci/jep/pull/295#discussion_r495468593 @daniel-beck points out that no such plugin exists on the update center.
Seems to have been a CloudBees proprietary plugin.
=> Removing jenkins-cloudfoundry-uaa

jep/227/compatibility.adoc, jep/228/compatibility.adoc
Noting releases of https://github.com/jfrog/jenkins-artifactory-plugin/pull/327, https://github.com/jenkinsci/splunk-devops-plugin/pull/13, and https://github.com/jenkinsci/xunit-plugin/pull/84.
=> Updates to compatibility tables

jep/227/compatibility.adoc
Only the version 3.9.3 was tested. The changes were introduced in 3.9.0-beta-1.
_(Artifactory was already updated by Jesse in https://github.com/jenkinsci/jep/commit/bad4f52b06ab02df85cf786f3bbe304ef4bd3049)_
@jeffret-b @jglick
=> [JEP-227] Update pipeline-maven

jep/227/compatibility.adoc
I had originally intended to delete this long-deprecated class, but that just complicated rollout and I eventually decided to just leave it alone.
=> CliAuthenticator no longer deleted

jep/227/README.adoc
Now that https://github.com/jenkinsci/jenkins/pull/4848 has been merged :tada: the japicmp reports from the PR build may break, depending on the orphaned item strategy, and there is no particular replacement other than the report for the `master` branch build in which the merge occurs, which will also be rotated out of history at some point. (Maybe in the future we should do something with the Checks API?)
=> [JEP-227] Links to japicmp report will be dead

jep/228/compatibility.adoc
This PR updates the JEP-228 compatibility table for sonarqube-plugin, as mentioned on https://github.com/SonarSource/sonar-scanner-jenkins/pull/171
=> Update JEP-228 compatibility for sonarqube-plugin

jep/221/README.adoc, jep/229/README.adoc
Various updates, but most importantly describing the successfully prototyped integration with Release Drafter and usage of self-published Actions to avoid duplication.
=> [JEP-229] Updates

jep/228/compatibility.adoc
https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/pull/203 and https://github.com/jenkinsci/nodejs-plugin/pull/36 have  been  released, so I'm updating the JEP-228 compatibility table to list the plugin versions.
CC @jglick
=> JEP-228: two PRs have been released, update compatibility table

jep/227/compatibility.adoc
Contrary to my expectations, it seems from https://github.com/jenkinsci/saml-plugin/pull/90#discussion_r582989685 that this patch did not in fact update the plugin to use Spring Security.
=> [JEP-227] Removing mention of saml-plugin#90

jep/227/compatibility.adoc
Reverts #351. Apparently deliberate behavior: https://github.com/spring-projects/spring-boot/issues/6140 / https://github.com/spring-projects/spring-security/issues/8140
=> [JEP-227] Revert note of crowd2

jep/229/README.adoc, jep/README.adoc
The title of JEP-229 confused me as it was talking about Jenkins
Components yet is equally applicaple to Jenkins plugins.
Normally a component would be something that goes into Jenkins like
`remoting` and one would not typically refer to a Plugin as a component.
This updates the title and the JEP body in a few places to make it clear
this is not just for components.
=> Update the title of Jep 229 to include plugins.

jep/7/README.adoc
https://github.com/stapler/stapler/pull/238#issuecomment-852409892
=> Also remove `stapler-jruby`

jep/228/compatibility.adoc
Follows up #378 to note https://github.com/jenkinsci/envinject-api-plugin/pull/17.
=> [JEP-228] Noting `envinject-api` fix

jep/227/README.adoc, jep/228/README.adoc, jep/README.adoc
I do not think we have any working formal definition of “accepted” after the loss of a BDFL but having the core PRs released as 2.266 seems the closest we can come.
=> Marking JEP-227 & JEP-228 accepted

jep/11/README.adoc
Just noticed it in the Google layout. Adoption process has been recently rewritten and migrated to GitHub. New page: https://jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/
This PR just adjusts the JEP to be aligned with the current state
=> JEP-11 - Update documentation to reflect the changes in the current process

jep/221/README.adoc, jep/229/README.adoc, jep/README.adoc
AFAIK JEP-221 was never fully prototyped, much less used; the discussions surrounding it led ultimately to JEP-229, which is now in active use. @daniel-beck confirm?
=> Mark JEP-221 withdrawn, and JEP-229 accepted

jep/0000/README.adoc
Describe the work to allow Jenkins core development to require Java 11 or newer.  Stop supporting build, test, or execution with Java 8.
=> Require Java 11 or newer

jep/235/README.adoc, jep/235/check-telemetry.sh
<details>
<summary>Telemetry up to and including most of March 3 (some stragglers)</summary>
```
[REPORTING STATS]
Instances reporting FilePath telemetry:
254903
Instances reporting non-empty FilePath telemetry:
1245
[PLUGIN POPULARITY STATS]
Instances reporting each of the known kinds of agent-to-controller FilePath calls:
577 maven-plugin$MavenBuildProxy2
294 log-parser
155 cobertura
113 publish-over-ssh
35 violations
28 maven-plugin$MavenSiteArchiver
22 hp-application-automation-tools-plugin
17 selenium
14 code-coverage-api
11 maven-plugin$AbstractMavenJavadocArchiver
10 jobcacher
6 analysis-core
3 xunit-2.0.2
2 warnings-ng-5.1.0
2 genexus
1 wildfly
1 webconlogparser
1 hp-application-automation-tools-plugin-5.3
1 ScriptConsole
```
</details>
Three new hits with just one more day to go: …
=> Final(ish) JEP-235 telemetry results

jep/230/README.adoc, jep/236/README.adoc
Updating a couple of JEPs to reflect https://github.com/jenkinsci/jenkins/pull/6543.
=> [JENKINS-51820] Java Web Start support has already been removed

jep/305/README.adoc
A minor part of the JEP-305 motivation was rendered obsolete by https://github.com/apache/maven/pull/381.
=> MNG-6754 fixed

jep/309/README.adoc, jep/README.adoc
Initially filed as #92 but never fully implemented and will no longer be used anywhere as of https://github.com/jenkinsci/jenkins/pull/7397. See https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/20, https://github.com/jenkinsci/git-plugin/pull/1357, https://github.com/jenkins-infra/pipeline-library/pull/525.
=> Mark JEP-309 as withdrawn

jep/236/README.adoc, jep/README.adoc
Goals of the JEP have been achieved as shown by the links included in the resolution section. Those links include:
* https://www.jenkins.io/blog/2022/06/28/require-java-11/ - Java 11 required for core (blog post)
* https://www.jenkins.io/blog/2022/12/14/require-java-11/ - Java 11 required for plugin development (blog post
* https://www.jenkins.io/doc/upgrade-guide/2.361/ - 2.361.1 upgrade guide
* https://www.jenkins.io/changelog-stable/#v2.361.1 - 2.361.1 changelog
* https://www.jenkins.io/changelog-old/#v2.357 - 2.357 changelog
Marking this JEP as `Accepted` per the definition in:
* https://github.com/jenkinsci/jep/blob/master/jep/1/README.adoc#accepted
Marking this JEP as `Final` per the definition in:
* https://github.com/jenkinsci/jep/blob/master/jep/1/README.adoc#finalizing-a-jep
=> [JEP-236] Require Java 11 is complete

jep-template/0000/README.adoc
Fixes several issues I have had with the template for a long time:
- Move the **Specification** section to after the **Reasoning** section. The current order has always seemed backwards to me. The **Specification** section essentially covers the implementation details of the solution. How is this to be understood by the reader if that reader does not first understand the problem and its high-level solution, which are covered in the **Motivation** and **Reasoning** sections? By way of analogy, when writing a mathematical proof, the proof *ends* with the thing you're trying to prove; it doesn't start with it. A mathematical proof starts with definitions, then proceeds to propositions, lemmas, corollaries, and ultimately the explanation of why a statement is true (the proof). This PR simply …
=> Improve template

jep-template/0000/README.adoc
Jenkins is 18 years old, and a recurring theme in the development of decades-old software is maintainability, which raises a much different set of challenges from those of initial greenfield development. One of the biggest challenges in software maintenance is migration management, and almost every Jenkins project I have worked on raises questions about forward compatibility if not itself implying a large-scale migration. My experience is that the upfront analysis of migration-related constraints at the time of project design can significantly benefit the project design, so this PR adds a **Migration** (i.e., forwards compatibility) section to the template after the **Backwards Compatibility** section. Experience shows that many projects succeed in isolation but fail to succeed in the …
=> Add migration section to template

jep/4/README.adoc
This PR updates the Kubernetes SIG Governance link from https://github.com/kubernetes/community/blob/master/sig-governance.md (not found) to https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md
=> [JEP-4] Update link to Kubernetes SIG Governance

jep-template/0000/README.adoc
The Jenkins project does not have dedicated project managers, so architects ought to consider the project management implications of their proposals. My personal experience has been that considering these implications at the time of project design can significantly improve the resulting design by identifying task dependency bottlenecks (and forcing the author to think about if and how they can be resolved) as well as staffing requirements (and forcing the author to revise the design if it is impractical within the realities of staffing constraints). Most importantly, the act of breaking down a prototype into the tasks needed to productize it serves as a forcing function to ensure that the prototype is complete enough to serve its purpose of informing a design. If a prototype is so …
=> Add a work estimate section to the template

jep/237/README.adoc
Expand the testing area for FIPS-140.
Detail that no automated checks will find all compliance issues so given we need to do a manual check there is little point in any automated checks for checking core/plugin compliance today.
fixes #404
```[tasklist]
```
=> Expand the testing area of JEP-237 (FIPS-140 support)
